title: "Nutritional Insights: Predicting Calories in Recipes"
description: >
  An analysis on caloric trends and nutrition information from a recipe dataset from food.com.
  Joyce Ku
  joyceku@umich.edu

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
