title: recipes-and-nutrition
description: "An analysis on caloric trends and nutrition information from a recipe dataset from food.com."

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
